### ISSUE TITLE
Small Typon in Makefile

### ISSUE THREAD

**Issue by Dist0rtion** [ParrotSec/parrot-raspberrypi-imgbuilder#2]
Just to let the Dev's know,..
There is a small typo at the end of the Makefile wich causes errors.. (at least for me)
At the last Line
```
write-and-resize:
sudo ./image-writer-resizer.sh $(BLOCKDEVICE)
```
There are Spaces instead of Tabulator..

**Comment by mibofra** [comment]
Fixed!
